// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: shorturl.proto
#ifndef GRPC_shorturl_2eproto__INCLUDED
#define GRPC_shorturl_2eproto__INCLUDED

#include "shorturl.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace shorturl {

// 服务定义
class ShortUrl final {
 public:
  static constexpr char const* service_full_name() {
    return "shorturl.ShortUrl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url& request, ::shorturl::Url* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>> AsyncGetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>>(AsyncGetShortUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>> PrepareAsyncGetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>>(PrepareAsyncGetShortUrlRaw(context, request, cq));
    }
    virtual ::grpc::Status GetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::shorturl::Url* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>> AsyncGetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>>(AsyncGetOriginalUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>> PrepareAsyncGetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>>(PrepareAsyncGetOriginalUrlRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url* request, ::shorturl::Url* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url* request, ::shorturl::Url* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey* request, ::shorturl::Url* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey* request, ::shorturl::Url* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>* AsyncGetShortUrlRaw(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>* PrepareAsyncGetShortUrlRaw(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>* AsyncGetOriginalUrlRaw(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::shorturl::Url>* PrepareAsyncGetOriginalUrlRaw(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url& request, ::shorturl::Url* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>> AsyncGetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>>(AsyncGetShortUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>> PrepareAsyncGetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>>(PrepareAsyncGetShortUrlRaw(context, request, cq));
    }
    ::grpc::Status GetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::shorturl::Url* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>> AsyncGetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>>(AsyncGetOriginalUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>> PrepareAsyncGetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shorturl::Url>>(PrepareAsyncGetOriginalUrlRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url* request, ::shorturl::Url* response, std::function<void(::grpc::Status)>) override;
      void GetShortUrl(::grpc::ClientContext* context, const ::shorturl::Url* request, ::shorturl::Url* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey* request, ::shorturl::Url* response, std::function<void(::grpc::Status)>) override;
      void GetOriginalUrl(::grpc::ClientContext* context, const ::shorturl::ShortKey* request, ::shorturl::Url* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::shorturl::Url>* AsyncGetShortUrlRaw(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::shorturl::Url>* PrepareAsyncGetShortUrlRaw(::grpc::ClientContext* context, const ::shorturl::Url& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::shorturl::Url>* AsyncGetOriginalUrlRaw(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::shorturl::Url>* PrepareAsyncGetOriginalUrlRaw(::grpc::ClientContext* context, const ::shorturl::ShortKey& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetShortUrl_;
    const ::grpc::internal::RpcMethod rpcmethod_GetOriginalUrl_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetShortUrl(::grpc::ServerContext* context, const ::shorturl::Url* request, ::shorturl::Url* response);
    virtual ::grpc::Status GetOriginalUrl(::grpc::ServerContext* context, const ::shorturl::ShortKey* request, ::shorturl::Url* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetShortUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetShortUrl() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetShortUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetShortUrl(::grpc::ServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetShortUrl(::grpc::ServerContext* context, ::shorturl::Url* request, ::grpc::ServerAsyncResponseWriter< ::shorturl::Url>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetOriginalUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetOriginalUrl() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetOriginalUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOriginalUrl(::grpc::ServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOriginalUrl(::grpc::ServerContext* context, ::shorturl::ShortKey* request, ::grpc::ServerAsyncResponseWriter< ::shorturl::Url>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetShortUrl<WithAsyncMethod_GetOriginalUrl<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetShortUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetShortUrl() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::shorturl::Url, ::shorturl::Url>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::shorturl::Url* request, ::shorturl::Url* response) { return this->GetShortUrl(context, request, response); }));}
    void SetMessageAllocatorFor_GetShortUrl(
        ::grpc::MessageAllocator< ::shorturl::Url, ::shorturl::Url>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::shorturl::Url, ::shorturl::Url>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetShortUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetShortUrl(::grpc::ServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetShortUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetOriginalUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetOriginalUrl() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::shorturl::ShortKey, ::shorturl::Url>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::shorturl::ShortKey* request, ::shorturl::Url* response) { return this->GetOriginalUrl(context, request, response); }));}
    void SetMessageAllocatorFor_GetOriginalUrl(
        ::grpc::MessageAllocator< ::shorturl::ShortKey, ::shorturl::Url>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::shorturl::ShortKey, ::shorturl::Url>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetOriginalUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOriginalUrl(::grpc::ServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOriginalUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetShortUrl<WithCallbackMethod_GetOriginalUrl<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetShortUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetShortUrl() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetShortUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetShortUrl(::grpc::ServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetOriginalUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetOriginalUrl() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetOriginalUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOriginalUrl(::grpc::ServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetShortUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetShortUrl() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetShortUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetShortUrl(::grpc::ServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetShortUrl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetOriginalUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetOriginalUrl() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetOriginalUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOriginalUrl(::grpc::ServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOriginalUrl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetShortUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetShortUrl() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetShortUrl(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetShortUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetShortUrl(::grpc::ServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetShortUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetOriginalUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetOriginalUrl() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetOriginalUrl(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetOriginalUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOriginalUrl(::grpc::ServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOriginalUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetShortUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetShortUrl() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::shorturl::Url, ::shorturl::Url>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::shorturl::Url, ::shorturl::Url>* streamer) {
                       return this->StreamedGetShortUrl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetShortUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetShortUrl(::grpc::ServerContext* /*context*/, const ::shorturl::Url* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetShortUrl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::shorturl::Url,::shorturl::Url>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetOriginalUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetOriginalUrl() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::shorturl::ShortKey, ::shorturl::Url>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::shorturl::ShortKey, ::shorturl::Url>* streamer) {
                       return this->StreamedGetOriginalUrl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetOriginalUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetOriginalUrl(::grpc::ServerContext* /*context*/, const ::shorturl::ShortKey* /*request*/, ::shorturl::Url* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetOriginalUrl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::shorturl::ShortKey,::shorturl::Url>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetShortUrl<WithStreamedUnaryMethod_GetOriginalUrl<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetShortUrl<WithStreamedUnaryMethod_GetOriginalUrl<Service > > StreamedService;
};

}  // namespace shorturl


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_shorturl_2eproto__INCLUDED
